apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fargate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-fargate
  template:
    metadata:
      labels:
        app: nginx-fargate
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-fargate-service
spec:
  selector:
    app: nginx-fargate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
