apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fg-eks-cluster
  region: us-west-2

nodeGroups:
  - name: ng-fargate
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
