---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster
  region: us-west-2
  version: "1.24"

availabilityZones:
  - us-west-2a
  - us-west-2b

vpc:
  cidr: 10.42.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

managedNodeGroups:
  - name: ng-1
    privateNetworking: true
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    tags:
      "ng-type": "managed"

iam:
  withOIDC: true
