---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kedaeks
  region: us-east-1
  version: "1.24"
availabilityZones:
  - us-east-1a
  - us-east-1b
managedNodeGroups:
  - name: general
    privateNetworking: true
    instanceType: t3.small
    desiredCapacity: 2
iam:
  withOIDC: true
