apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: development
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: license-key
      mountPath: /root/key.txt
      subPath: key.txt 
    env:
    - name: "DB_USER"
      valueFrom:
         secretKeyRef:
           name: db-secret
           key: db_user
    - name: "DB_PASSWORD"
      valueFrom:
          secretKeyRef:
             name: db-secret
             key: db_pass
  restartPolicy: Always
  volumes:
  - name: license-key
    secret:
       secretName: my-secret
       items:
       - key: licensekey
         path: key.txt
